joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_rate 100

# whole_body_controller: &whole_body_controller
#   type: position_controllers/JointTrajectoryController  
#   joints:
#     - torso_lift_joint
#     - r_upper_arm_roll_joint
#     - r_shoulder_pan_joint
#     - r_shoulder_lift_joint
#     - r_forearm_roll_joint
#     - r_elbow_flex_joint
#     - r_wrist_flex_joint
#     - r_wrist_roll_joint
#     - l_upper_arm_roll_joint
#     - l_shoulder_pan_joint
#     - l_shoulder_lift_joint
#     - l_forearm_roll_joint
#     - l_elbow_flex_joint
#     - l_wrist_flex_joint
#     - l_wrist_roll_joint
#     - head_pan_joint
#     - head_tilt_joint
#   gains:
#     torso_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     r_upper_arm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     r_shoulder_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     r_shoulder_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     r_forearm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     r_elbow_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     r_wrist_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     r_wrist_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     l_upper_arm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     l_shoulder_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     l_shoulder_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     l_forearm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     l_elbow_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     l_wrist_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     l_wrist_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     head_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#     head_tilt_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
#   constraints:
#     stopped_velocity_tolerance: 0

l_gripper_l_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - l_gripper_l_finger_joint
  gains: 
    l_gripper_l_finger_joint: { p: 2000, i: 100, d: 50 }

r_gripper_l_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - r_gripper_l_finger_joint
  gains: 
    r_gripper_l_finger_joint: { p: 2000, i: 100, d: 50 }

r_body_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - r_upper_arm_roll_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - head_pan_joint
    - head_tilt_joint
    - torso_lift_joint
  gains:
    torso_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_upper_arm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_shoulder_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_shoulder_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_forearm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_elbow_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_wrist_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    r_wrist_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    head_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    head_tilt_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
  constraints:
    stopped_velocity_tolerance: 0

# real time controllers
real_time_position_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - torso_lift_joint
    - r_upper_arm_roll_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_upper_arm_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
    - head_pan_joint
    - head_tilt_joint
    - l_gripper_l_finger_joint
    - r_gripper_l_finger_joint
  torso_lift_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_upper_arm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_shoulder_pan_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_shoulder_lift_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_forearm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_elbow_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_wrist_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_wrist_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_upper_arm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_shoulder_pan_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_shoulder_lift_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_forearm_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_elbow_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_wrist_flex_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_wrist_roll_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  head_pan_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  head_tilt_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  l_gripper_l_finger_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}
  r_gripper_l_finger_joint:
    pid: {p: 2000, i: 100, d: 50, i_clamp: 10}

torso_lift_position_controller:
  type: effort_controllers/JointPositionController
  joint: torso_lift_joint
  pid: { p: 2000, i: 100, d: 50 }
r_upper_arm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_upper_arm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
r_shoulder_pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_shoulder_pan_joint
  pid: { p: 2000, i: 100, d: 50 }
r_shoulder_lift_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_shoulder_lift_joint
  pid: { p: 2000, i: 100, d: 50 }
r_forearm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_forearm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
r_elbow_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_elbow_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
r_wrist_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_wrist_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
r_wrist_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_wrist_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
l_upper_arm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_upper_arm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
l_shoulder_pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_shoulder_pan_joint
  pid: { p: 2000, i: 100, d: 50 }
l_shoulder_lift_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_shoulder_lift_joint
  pid: { p: 2000, i: 100, d: 50 }
l_forearm_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_forearm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
l_elbow_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_elbow_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
l_wrist_flex_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_wrist_flex_joint
  pid: { p: 2000, i: 100, d: 50 }
l_wrist_roll_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_wrist_roll_joint
  pid: { p: 2000, i: 100, d: 50 }
head_pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_pan_joint
  pid: { p: 2000, i: 100, d: 50 }
head_tilt_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_tilt_joint
  pid: { p: 2000, i: 100, d: 50 }

# velocity controllers
vel_gains: &vel_gains
  p: 200.0
  i: 1000.0
  d: 0.1
  i_clamp: 10.0
torso_lift_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: torso_lift_joint
  pid: *vel_gains
r_upper_arm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_upper_arm_roll_joint
  pid: *vel_gains
r_shoulder_pan_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_shoulder_pan_joint
  pid: *vel_gains
r_shoulder_lift_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_shoulder_lift_joint
  pid: *vel_gains
r_forearm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_forearm_roll_joint
  pid: *vel_gains
r_elbow_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_elbow_flex_joint
  pid: *vel_gains
r_wrist_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_wrist_flex_joint
  pid: *vel_gains
r_wrist_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: r_wrist_roll_joint
  pid: *vel_gains
l_upper_arm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_upper_arm_roll_joint
  pid: *vel_gains
l_shoulder_pan_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_shoulder_pan_joint
  pid: *vel_gains
l_shoulder_lift_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_shoulder_lift_joint
  pid: *vel_gains
l_forearm_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_forearm_roll_joint
  pid: *vel_gains
l_elbow_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_elbow_flex_joint
  pid: *vel_gains
l_wrist_flex_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_wrist_flex_joint
  pid: *vel_gains
l_wrist_roll_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: l_wrist_roll_joint
  pid: *vel_gains
head_pan_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: head_pan_joint
  pid: *vel_gains
head_tilt_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: head_tilt_joint
  pid: *vel_gains







left_controller:
  type: position_controllers/JointTrajectoryController  
  joints: 
    - l_upper_arm_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
  gains:
    l_upper_arm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_shoulder_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_shoulder_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_forearm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_elbow_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_wrist_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    l_wrist_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
  constraints:
    stopped_velocity_tolerance: 0


l_gripper_l_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - l_gripper_l_finger_joint
  gains:
    l_gripper_l_finger_joint: { p: 2000, i: 100, d: 50 }

r_gripper_l_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - r_gripper_l_finger_joint
  gains: 
    r_gripper_l_finger_joint: { p: 2000, i: 100, d: 50 }

cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "l_gripper_tool_frame"
    robot_base_link: "torso_lift_link"
    ft_sensor_ref_link: "l_force_torque_link"
    compliance_ref_link: "l_gripper_tool_frame"
    target_frame_topic: "l_gripper_tool_frame"
    joints:
      - l_upper_arm_roll_joint
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_forearm_roll_joint
      - l_elbow_flex_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint

    stiffness:  # w.r.t. compliance_ref_link
        trans_x: 500
        trans_y: 500
        trans_z: 500
        rot_x: 20
        rot_y: 20
        rot_z: 20

    solver:
        error_scale: 1.5 # up to 2.0 was nice in free space
        iterations: 1

    pd_gains:
        trans_x: {p: 0.05}
        trans_y: {p: 0.05}
        trans_z: {p: 0.05}
        rot_x: {p: 1.5}
        rot_y: {p: 1.5}
        rot_z: {p: 1.5}

# joint_to_cartesian_controller:
#     type: "cartesian_controllers/JointControllerAdapter"
#     end_effector_link: "l_gripper_tool_frame"
#     robot_base_link: "base_link"
#     target_frame_topic: "/my_cartesian_motion_controller/target_frame"
#     joints:
#     - joint1
#     - joint2
#     - joint3
#     - joint4
#     - joint5
#     - joint6

#     joint_limits:
#       joint1:
#         has_velocity_limits: true
#         max_velocity: 3.15
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint2:
#         has_velocity_limits: true
#         max_velocity: 3.15
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint3:
#         has_velocity_limits: true
#         max_velocity: 3.15
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint4:
#         has_velocity_limits: true
#         max_velocity: 3.2
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint5:
#         has_velocity_limits: true
#         max_velocity: 3.2
#         has_acceleration_limits: true
#         max_acceleration: 10.0
#       joint6:
#         has_velocity_limits: true
#         max_velocity: 3.2
#         has_acceleration_limits: true
#         max_acceleration: 10.0
